var map =[[
"bbbbbbbbbbbbbbbbbbbbbbbbb",		//Level 1
"bsssllllssllllslslssslllb",
"bllllsslslllllssssllllllb",
"bblslslsllldddddlbbbbbbbb",
"bblllllllddddddddddddlllb",
"bbbblslddsddddddddddllllb",
"bbbbbblssssldddddslslsllb",
"bsssllllssllllslslssslllb",
"bllllsslslllddddssllllllb",
"bllllsslsllllddsssllllllb",
"bsssllllssllllbbbbbbbbbbb",
"blllllssssllsslslslslsllb",
"bllllsslslllllssssllllllb",
"blslslsllllsssslslssslllb",
"blllllssssllsslslslslsllb",
"bllllsslslllllssssllllllb",
"bllllsslslllllssssllllllb",
"blllllssssllsslslslslsllb",
"bllllsslslllllssssllllllb",
"blslslslllllllslslssslllb",
"blllllsbssllsslslslslsllb",
"bllllssbblllllssssllllllb",
"bllllssbblllllssssllllllb",
"bsssllbbbsllllslslssslllb",
"bbbbbbbbbbbbbbbbbbbbbbbbb"],

["bbbbbbbbbbbbbbbbbbbbbbbbb",	//Level 2
"bsssllllssllllslslssslllb",
"bllllsslslllllssssllllllb",
"bblslslsllldddddlbbbbbbbb",
"bbllbbbbbbbbbdbbbbbbbbblb",
"bbbblslddsddddddddddllllb",
"bbbbbblssssldddddslslsllb",
"bsssllllssllllslslssslllb",
"bllllsslslllddddssllllllb",
"bllllsslsllllddsssllllllb",
"bsssllllssllllbbbbbbbbbbb",
"blllllssssllsslslslslsllb",
"bllllsslslllllssssllllllb",
"blslslsllllsssslslssslllb",
"blllllssssllsslslslslsllb",
"bllllsslslllllssssllllllb",
"bllllsslslllllssssllllllb",
"blllllssssllsslslslslsllb",
"bllllsslslllllssssllllllb",
"blslslslllllllslslssslllb",
"blllllsbssllsslslslslsllb",
"bllllssbblllllssssllllllb",
"bllllssbblllllssssllllllb",
"bsssllbbbsllllslslssslllb",
"bbbbbbbbbbbbbbbbbbbbbbbbb"]];

